### ISSUE TITLE
[BUG] | Broken images.

### ISSUE THREAD

**Issue by ivanosquis10** [dscnitrourkela/project-raisin#83]
### Description

The images are broken, do not display properly and make the project look incomplete :(
![image](https://github.com/dscnitrourkela/project-raisin/assets/83567373/c9d6d0f3-15e4-45f1-a431-e95d19904cda)
![image](https://github.com/dscnitrourkela/project-raisin/assets/83567373/0189d215-0ef0-44b6-ab61-cb3c399b979a)

### Expected behavior

Show the images

### Actual behavior

The images are not visible anywhere.

### Possible fix

check the links or where the images are saved (if any) and generate new links or new images.

### Steps to reproduce

![image](https://github.com/dscnitrourkela/project-raisin/assets/83567373/03b3a9e3-e6cb-48f1-9eb9-ed5968ce6c91)

### Context

The project looks incomplete :(

**Comment by ashutosh-rath02** [comment]
Hey @ivanosquis10 the work on the latest version is WIP. We have this issue resolved there😊
